### PR TITLE
Add requestFormat in endpoint schemas

### PR DESCRIPTION
**Pull request by aharisu**
related #47

### CODE REVIEW

**Comment by astahmer** [comment]
LGTM, thank you for working on this ! 🙏 
could you add a [changeset](https://github.com/changesets/changesets/blob/main/docs/intro-to-using-changesets.md) ?

**Comment by aharisu** [comment]
Thank you!
Adding a changeset is also OK👍

**Comment by astahmer** [comment]
whoops I just realized you hadnt yet added one, my bad I merged too soon 😓

**Comment by aharisu** [comment]
Sorry for the delay in adding this. 
Please review this PR #49

**Pull request merged**
